version: '3'

services:
  web:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - db
      - app
    networks:
      - app-nginx-node-network
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - db
    networks:
      - app-nginx-node-network
  db:
    image: mysql:8.3.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./node/.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: people_db
    networks:
      - app-nginx-node-network

networks:
  app-nginx-node-network:
    driver: bridge